spring:
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/places"
    username: "springuser"
    password: "Spring123."
  jpa:
    hibernate:
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
