spring:
  application:
    name: 'places'
  datasource:
    url: jdbc:mysql://localhost:3306/places
    username: root
    password: admin123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false

security:
    ignored: /swagger-resources/**
